### ISSUE TITLE
关于flex.css

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/react-cnode#20]
github地址：[github: flex.css](https://github.com/lzxb/flex.css)
演示地址：[flex.css](http://lzxb.name/flex.css/)

**Comment by ckinmind** [comment]
- flex只有两个属性，一个是容器属性flex，一个是子元素属性flex-box 
```css
[data-flex] {
    overflow: hidden;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
}

[data-flex-box="0"] {
    -webkit-box-flex: 0;
    -webkit-flex-grow: 0;
    -ms-flex-positive: 0;
    flex-grow: 0;
    -webkit-flex-shrink: 0;
    -ms-flex-negative: 0;
    flex-shrink: 0;
}

<header className="common-header" data-flex>
      <div className="icon" data-flex="main:center cross:center" data-flex-box="0"></div>
     ...
</header>
```
