### ISSUE TITLE
关于animation动画(keyframes)

### ISSUE THREAD

**Issue by ckinmind** [ckinmind/react-cnode#21]
**1. 下滑动画**
```css
.common-header {
    height: 50px;
    z-index: 999;
    position: relative;
    background: @style-main;
    animation: move-down 0.3s ease-out;
}
@keyframes move-down {
    0% {
        transform: translate(0, -10px);
    }
    100% {
        transform: translate(0, 0);
    }
}
```
